---
# Products available by region
# https://azure.microsoft.com/en-us/global-infrastructure/services/

- name: Create web application deployment
  azure_rm_deployment:
    state: present
    name: "{{app_name}}"
    resource_group: "{{az_group}}"
