---
# Required playbook vars: app_name

az_account_type: Standard_LRS
az_location: "South Central US"
az_group: "{{app_name}}Group"
# 'az_plan' must be between 3-24 chars, only lowercase or numbers
# TODO: replace() will use regex to strip ALL special characters
az_plan: "{{app_name | trim | replace('_', '') | truncate(20) | lower}}plan"
app_server: "{{app_name}}_server"
app_db: "{{app_name}}_db"

# Other module options:
# 	- security group
# 	- public ip
# 	- load balancer
#   - azure image
